// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/signup": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/redeem": {
    params: {};
  };
  "/portal": {
    params: {};
  };
  "/auth/github": {
    params: {};
  };
  "/auth/github/callback": {
    params: {};
  };
  "/auth/google": {
    params: {};
  };
  "/auth/google/callback": {
    params: {};
  };
  "/api/trpc/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/signup" | "/dashboard" | "/redeem" | "/portal" | "/auth/github" | "/auth/github/callback" | "/auth/google" | "/auth/google/callback" | "/api/trpc/*";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/signup.tsx": {
    id: "routes/signup";
    page: "/signup";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/dashboard";
  };
  "routes/redeem.tsx": {
    id: "routes/redeem";
    page: "/redeem";
  };
  "routes/portal.tsx": {
    id: "routes/portal";
    page: "/portal";
  };
  "routes/auth/github.tsx": {
    id: "routes/auth/github";
    page: "/auth/github";
  };
  "routes/auth/github.callback.tsx": {
    id: "routes/auth/github.callback";
    page: "/auth/github/callback";
  };
  "routes/auth/google.tsx": {
    id: "routes/auth/google";
    page: "/auth/google";
  };
  "routes/auth/google.callback.tsx": {
    id: "routes/auth/google.callback";
    page: "/auth/google/callback";
  };
  "routes/api.trpc.$.tsx": {
    id: "routes/api.trpc.$";
    page: "/api/trpc/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/signup": typeof import("./app/routes/signup.tsx");
  "routes/dashboard": typeof import("./app/routes/dashboard.tsx");
  "routes/redeem": typeof import("./app/routes/redeem.tsx");
  "routes/portal": typeof import("./app/routes/portal.tsx");
  "routes/auth/github": typeof import("./app/routes/auth/github.tsx");
  "routes/auth/github.callback": typeof import("./app/routes/auth/github.callback.tsx");
  "routes/auth/google": typeof import("./app/routes/auth/google.tsx");
  "routes/auth/google.callback": typeof import("./app/routes/auth/google.callback.tsx");
  "routes/api.trpc.$": typeof import("./app/routes/api.trpc.$.tsx");
};